Fix: Do not check if crytsetup binary exists

diff --git a/scripts/max-secure-luks-format b/scripts/max-secure-luks-format
--- a/scripts/max-secure-luks-format
+++ b/scripts/max-secure-luks-format
@@ -5,7 +5,8 @@ set -o errexit -o nounset -o pipefail
 function desc  { echo "Create a LUKS dm-crypt volume with very secure crypto/hash settings"; }
 function usage { echo "Usage: $(basename ${0}) BLOC_DEVICE"; }
 if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
-OK=1; cryptsetup > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "cryptsetup not found"; exit 1; fi
+# We cannot check the cyptsetup binary as we are not root yet.
+# OK=1; which cryptsetup > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "cryptsetup not found"; exit 1; fi
 
 
 if [ ${#} -ne 1 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi
