Implement Valgrind scripts: memcheck, helgrind, drd, exp-sgcheck

diff --git a/scripts/max-exhaustive-valgrind-memcheck b/scripts/max-exhaustive-valgrind-memcheck
--- a/scripts/max-exhaustive-valgrind-memcheck
+++ b/scripts/max-exhaustive-valgrind-memcheck
@@ -1,18 +1,17 @@
 #!/bin/bash
-
-# Runs optipng with slowest settings to archieve maximum PNG file compression.
-
-
 set -o errexit -o nounset -o pipefail
-# SCRIPT_FILENAME=$(readlink -f $0)
-# SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
-# DOTFILES_PATH=${SCRIPT_PATH}/../..
 
-# source ${DOTFILES_PATH}/lib/bivalvia/help.sh
+# Command line parameter parsing and dependency checks.
+function desc  { echo "Runs the valgrind helgrind tool with settings for to find maximum numbers of errors"; }
+function usage { echo "Usage: max-exhaustive-valgrind-exp-sgcheck EXECUTABLE"; }
+if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
+OK=1; which valgrind > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "valgrind not found"; exit 1; fi
 
 
-if [ ${#} != "1" ]; then
-    invalid_parameter_exit
-fi
+if [ ${#} -ne 1 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi
 
-optipng -o7 ${1}
+EXECUTABLE=${1}
+TOOL_OPTIONS="--tool=memcheck --leak-check=full --track-origins=yes --show-reachable=yes --show-leak-kinds=all --errors-for-leak-kinds=all"
+GLOBAL_OPTION="-q --error-exitcode=9 --trace-children=yes --num-callers=50"
+
+valgrind ${GLOBAL_OPTION} ${TOOL_OPTIONS} ${EXECUTABLE}
